version: '3.7'
##############
# Containers #
##############
services:
  ########
  # Plex #
  ########
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      # - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TIME_ZONE}
      - PLEX_CLAIM=${PLEX_CLAIM_CODE}
    hostname: plex
    volumes:
      - ${PATH_MEDIA}:/media
      - ${PATH_PLEX}/config:/config
      - ${PATH_PLEX}/transcode:/transcode
      - ${PATH_MEDIA}:/data
  ##############
  # Jellyfin   #
  ##############
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - JELLYFIN_PublishedServerUrl=192.168.0.40 #optional
    volumes:
      - ${PATH_JELLYFIN}/config:/config
      - ${PATH_MEDIA}:/data/tvshows
      - ${PATH_MEDIA}:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
      ############
      # Tautulli #
      ############
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: unless-stopped
    ports:
      - 8181:8181/tcp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    hostname: tautulli
    volumes:
      - ${PATH_DOCKER}/tautulli/config:/config
  ###########
  # Jackett #
  ###########
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117/tcp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    hostname: jackett
    volumes:
      - ${PATH_DOCKER}/jackett/config:/config
      - ${PATH_DOWNLOAD}:/downloads
  ################
  # FlareSolverr #
  ################
  flare-solver:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    ports:
      - 8191:8191
  # ##########
  # # Lidarr #
  # ##########
  # lidarr:
  #   container_name: lidarr
  #   image: linuxserver/lidarr:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8686:8686/tcp
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIME_ZONE}
  #   hostname: lidarr
  #   volumes:
  #     - ${PATH_DOCKER}/lidarr/config:/config
  #     - ${PATH_DOWNLOAD}:/downloads
  #     - ${PATH_MEDIA}/Musics:/media
  ##########
  # Radarr #
  ##########
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878/tcp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    hostname: radarr
    volumes:
      - ${PATH_DOCKER}/radarr/config:/config
      - ${PATH_DOWNLOAD}:/downloads
      - ${PATH_MEDIA}/Films:/media
  ##########
  # Sonarr #
  ##########
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989/tcp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    hostname: sonarr
    volumes:
      - ${PATH_DOCKER}/sonarr/config:/config
      - ${PATH_DOWNLOAD}:/downloads
      - ${PATH_DOWNLOAD}:/data
      - ${PATH_MEDIA}:/media
  # #########
  # # Beets #
  # #########
  # beets:
  #   container_name: beets
  #   image: linuxserver/beets:latest
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIME_ZONE}
  #   labels:
  #     - stack=media
  #   hostname: beets
  #   volumes:
  #     - ${PATH_DOCKER}/beets/config:/config
  #     - ${PATH_DOCKER}/beets/downloads/:/downloads
  #     - ${PATH_MEDIA}/Musics:/music
  #   ports:
  #     - 8337:8337
  #   restart: unless-stopped
  ################
  # Transmission #
  ################
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - ${PATH_DOCKER}/transmission/config:/config
      - ${PATH_DOWNLOAD}:/data
      - ${PATH_DOWNLOAD}:/downloads
      - ${PATH_DOWNLOAD}:/watch
      - ${PATH_MEDIA}:/media
  ##############
  # EmulatorJS #
  ##############
  # emulatorjs:
  #   image: lscr.io/linuxserver/emulatorjs:latest
  #   container_name: emulatorjs
  #   restart: unless-stopped
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIME_ZONE}
  #     - SUBFOLDER=/ # optional
  #   volumes:
  #     - ${PATH_DOCKER}/emulatorjs/config:/config
  #     - ${PATH_EMULATOR}:/data
  #   ports:
  #     - 3000:3000
  #     # - 80:80
  #     # - 4001:4001 # optional
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - ${TA_PATH_MEDIA}:/youtube
      - cache:/cache
      # - ${PATH_DOCKER}/tubearchivist/resolv.conf:/etc/resolv.conf
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=${PUID}
      - HOST_GID=${PGID}
      - TZ=${TIME_ZONE}
      - TA_HOST=${TA_HOSTNAME}
      - TA_USERNAME=${TA_USERNAME}
      - TA_PASSWORD=${TA_PASSWORD}
      - ELASTIC_PASSWORD=${TA_ELASTIC_PASSWORD}
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es # only for amd64, or use official es 8.5.1
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=${TA_ELASTIC_PASSWORD}"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data # check for permission error when using bind mount, see readme
    expose:
      - "9200"
volumes:
  cache:
  redis:
  es:
